# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: sync reference from rkaitplace

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Python deps
        run: pip install pillow requests numpy

      - name: Run sync
        run: python ./sync_template_from_rkaitplace.py
        
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
        
      - name: check for changes
        run: git status
        
      - name: Commit report
        run: |
            git config --global user.name 'drbaka-de'
            git config --global user.email 'drbaka-de@users.noreply.github.com'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git add .
            git commit -am "sync image"
            git push
